# Generated by Django 3.0.8 on 2020-10-14 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='staffs',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('staff_fname', models.CharField(max_length=50)),
                ('staff_lname', models.CharField(max_length=50)),
                ('staff_email', models.CharField(max_length=100)),
                ('staff_gender', models.CharField(max_length=2)),
                ('staff_username', models.CharField(max_length=50)),
                ('staff_password', models.CharField(max_length=50)),
                ('staff_address', models.TextField()),
                ('staff_contactnumber', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('student_email', models.CharField(max_length=100)),
                ('student_gender', models.CharField(max_length=2)),
                ('student_username', models.CharField(max_length=50)),
                ('student_password', models.CharField(max_length=50)),
                ('student_address', models.TextField()),
                ('student_course', models.CharField(max_length=50)),
                ('student_contactnumber', models.CharField(max_length=10)),
                ('student_createdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feedback_id', models.IntegerField(primary_key=True, serialize=False)),
                ('feedback_message', models.TextField()),
                ('feedback_date', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.students')),
            ],
        ),
        migrations.CreateModel(
            name='exam',
            fields=[
                ('exam_id', models.IntegerField(primary_key=True, serialize=False)),
                ('exam_markattendance', models.CharField(max_length=5)),
                ('exam_date', models.DateTimeField()),
                ('exam_marks', models.IntegerField()),
                ('exam_subject', models.CharField(max_length=50)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.students')),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('attendance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('attendance_markattendance', models.CharField(max_length=5)),
                ('attendance_date', models.DateTimeField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.staffs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.students')),
            ],
        ),
    ]
