# Generated by Django 3.0.8 on 2020-10-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='student_name',
            new_name='student_fname',
        ),
        migrations.AddField(
            model_name='students',
            name='student_lname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
