# Generated by Django 3.0.8 on 2020-10-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201018_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_createdate',
            field=models.DateTimeField(null=True),
        ),
    ]
