# Generated by Django 3.0.8 on 2020-10-19 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201018_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='staff',
        ),
    ]
