# Generated by Django 3.0.8 on 2020-10-21 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_extenduser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='extenduser',
        ),
    ]
