# Generated by Django 3.0.8 on 2020-11-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201103_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
